# Generated by Django 2.1 on 2019-02-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20181220_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_edit', 'Can CRUD Authors'),)},
        ),
    ]
